### ISSUE TITLE
Consider adding typescript

### ISSUE THREAD

**Issue by VityaSchel** [tremby/json-multi-parse#2]
Temp fix:
add this to json-multi-parse.d.ts
```ts
declare module 'json-multi-parse' {
  const jsonMultiParse: JSON.parse
  export default jsonMultiParse
}
```

**Comment by tremby** [comment]
If you open a PR for that and verify it's working I'll merge it.

**Comment by tremby** [comment]
Oh, it looks like TS types were added some time ago too thanks to another contributor; they would have been published just now. Please reopen if something's wrong!
