### ISSUE TITLE
Fix for newer versions of Chrome (I'm lazy to create pull request)

### ISSUE THREAD

**Issue by VityaSchel** [tremby/json-multi-parse#3]
Add 
```
/^()()Unexpected non-whitespace character after JSON at position (\d+) \(line \d+ column \d+\)$/ // Chrome 119
```
to `ERROR_REGEXES` in index.js file as a third item in array.

patch file:
```patch
diff --git a/index.js b/index.js
index 6469b811f0fa38eb442c4321cc17ba5810c2a4cb..ebb279f370de23c87d65808c73b7167f74f42e8f 100644
--- a/index.js
+++ b/index.js
@@ -10,6 +10,7 @@ const {splitByIndex, splitByLineAndChar} = require('./split');
 const ERROR_REGEXES = [
 	/^()()Unexpected token { in JSON at position (\d+)$/, // Node 8, Chrome 69
 	/^JSON.parse: unexpected non-whitespace character after JSON data at line (\d+) column (\d+) of the JSON data()$/, // Firefox 62
+	/^()()Unexpected non-whitespace character after JSON at position (\d+) \(line \d+ column \d+\)$/ // Chrome 119
 ];
 
 /**
```

**Comment by VityaSchel** [comment]
Tested by me, this library works with this regex now

**Comment by VityaSchel** [comment]
alright Ill do this

**Comment by VityaSchel** [comment]
I just found that you already added this 6 months ago, looks like you forgot to publish new version to npm!
no need for pr :)

**Comment by VityaSchel** [comment]
@tremby just so you know: npm still has 1.2.0 version of this package, while on github it seems to be 1.3.1
<img width="435" alt="image" src="https://github.com/tremby/json-multi-parse/assets/59040542/1f5b6192-18a0-48c9-af99-178fe39c6cb1">
https://www.npmjs.com/package/json-multi-parse

<img width="246" alt="image" src="https://github.com/tremby/json-multi-parse/assets/59040542/48a3176f-a7ba-4dff-8741-a99c8e9b149d">

**Comment by tremby** [comment]
Oops, guess I forgot to publish when that change was added 6 months ago! Published just now. Thanks for the heads up.
